config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics, only: [:autocomplete] do
    collection do
      get :autocomplete, defaults: { format: 'json' }
    end
  end

  resources :locations, only: [:autocomplete] do
    collection do
      get :autocomplete, defaults: { format: 'json' }
    end
  end

  scope "(:locale)", locale: /en|ja/ do
    resources :subscriptions, except: [:destroy], param: :uid do
      collection do
        get :search
        post :results
      end
    end

    resources :rich_subscriptions, except: [:destroy, :index], param: :uid

    resources :simple_search, except: [:destroy], param: :uid

    get '/unsubscribe', to: 'cancellations#new'
    post '/unsubscribe', to: 'cancellations#submit'
    get '/unsubscribing', to: 'cancellations#sent'
    get '/unsubscribe/:unsubscribe_uid', to: 'cancellations#destroy', as: 'unsubscriber'

    get '/about', to: 'static_pages#about'
    get '/privacy', to: 'static_pages#privacy'
  end

  get '/test_ip', to: 'subscriptions#test_ip'

  mount_griddler '/incoming/mail'

  get '/t/:topic_uid/l/:location_uid', to: 'subscriptions#search'
  get '/t/:topic_uid', to: 'subscriptions#search'

  get '/l/:location_uid/t/:topic_uid', to: 'subscriptions#search'
  get '/l/:location_uid', to: 'subscriptions#search'

  # get '/simple', to: 'subscriptions#new', defaults: { map: false }, as: :simple_form
  # get '/map', to: 'subscriptions#new', defaults: { map: true }, as: :map
  get '/:locale', to: 'subscriptions#search'
  root 'rich_subscriptions#new'

  match '*any', to: 'application#options', :via => [:options]

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :location, dependent: :destroy
  belongs_to :topic
  belongs_to :user
  accepts_nested_attributes_for :location, :topic, :user
  validates_associated :location, :topic, :user
  before_validation do
    find_and_validate_associated_records
  end
  after_validation do
    self.errors.delete(:location)
    self.errors.delete(:user)
    self.errors.delete(:topic)
  end
  before_create do
    generate_uids
    activate
  end

  def activate
    self.active = true
    self.location.active = true
  end

  def safely_destroy
    self.location.active = false
    self.active = false
    self.user.destroy if self.user.subscriptions.count.zero?
    return true if self.save and self.location.save
  end

  def generate_uids
    self.uid = generate_code(7)
    self.mailing_uid = generate_code(7)
    self.unsubscribe_uid = generate_code(20)
  end

  def find_nearby_posters
    # Temporary. Replace.
    self.location.geocode_as_needed
    find_topic if self.topic.id.nil?
    unless self.topic.id.nil?
      locations = self.location.find_nearby_locations.map do |location|
        location.id if location and location.active
      end
      Subscription.where(location_id: locations, topic_id: self.topic.id)
    else
      []
    end
  end

  def find_nearby_listeners
    # Temporary. Garbage! Replace.
    self.location.geocode_as_needed
    find_topic if self.topic.id.nil?
    unless self.topic.id.nil?
      locations = self.location.find_nearby_coverages.map do |location|
        location.id if location and location.active
      end
      Subscription.where(location_id: locations, topic_id: self.topic.id)
    else
      []
    end
  end

  def nearby_posters
    # Replacement for find_nearby_posters
    # Far more efficient query
    self.location.geocode_as_needed
    find_topic if self.topic.id.nil?
    unless self.topic.id.nil?
      Subscription.where(
        location_id: self.location.nearbys(
          location.radius_in_miles,
          select: "id",
          select_distance: false,
          select_bearing: false),
        topic_id: self.topic.id,
        active: true)
    else
      []
    end
  end

  def nearby_listeners
    # Replacement for find_nearby_listeners
    # Need to dive deep into ActiveRecord to figure this out
    self.location.geocode_as_needed
    find_topic if self.topic.id.nil?
    unless self.topic.id.nil?
      []
    else
      []
    end
  end

  def find_topic
    if self.topic_id.nil? and self.topic.name.present?
      # The arel_table lets us search case insensitive.
      self.topic = Topic.where(Topic.arel_table[:name].matches(self.topic.name)).first_or_initialize(name: self.topic.name)
    end
  end

  def find_and_validate_associated_records
    if self.user_id.nil? and self.user.email.present?
      # First, check to see if this user already exists.
      user_query = User.where(email: self.user.email)
      if user_query.present?
        # Since the user already exists, associate it with this new subscription.
        self.user = user_query.first
        if self.topic_id.nil? and self.topic.name.present?
          # Next, check to see if this topic already exists.
          topic_query = Topic.where(Topic.arel_table[:name].matches(self.topic.name))
          if topic_query.present?
            # Like with the user, associate the existing topic with this new subscription.
            self.topic = topic_query.first
            # We now know that this user is already subscribed to this topic.
            # It's okay to be subscribed in multiple locations, but we want to make sure this isn't a dupe.
            self.location.geocode_as_needed
            location_query = Location.joins(subscription: [:topic, :user])
                                     .where(subscriptions: {active: true},
                                            topics: {name: self.topic.name},
                                            locations: {latitude: self.location.latitude,
                                                        longitude: self.location.longitude},
                                            users: {email: self.user.email})
            if location_query.present?
              # User already has a subscription to this topic at this location.
              # This is no good so we need to add some errors.
              if self.location.radius_units.present? and self.location.radius_length.present?
                if location_query.first.radius_length_in_meters == self.location.radius_in_meters
                  errors.add(:location_id, :taken_with_exact_radius)
                else
                  errors.add(:location_id, :taken_with_new_radius)
                end
              end
            else
              # Existing topic, new location.
              # Topic was already associated to the subscription previously, so nothing to do here.
              # Let everything pass through.
            end
          else
            # New topic, new location.
            # Nothing to do here, let everything pass through.
          end
        end
      else
        # New user.
        # Associate existing topic and let the location be unique.
        find_topic
      end
    end
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def search
    @topic_uid = params[:topic_uid]
    @location_uid = params[:location_uid]
    @topic = if @topic_uid.present? then
      Topic.where(uid: params[:topic_uid]).first_or_initialize
    else
      Topic.new
    end
    @location = if @location_uid.present? then
      Location.where(uid: params[:location_uid]).first_or_initialize
    else
      Location.new
    end
  end

  def results
    if topic_params[:name].present?
      @topic = Topic.where(Topic.arel_table[:name].matches(topic_params[:name])).first_or_initialize(name: topic_params[:name])
    else
      @topic = Topic.new(topic_params)
    end
    @location = Location.new(location_params)
    y = @topic.valid?
    z = @location.valid?
    if y and z
      @subscription = Subscription.new
      @subscription.build_topic(@topic.attributes)
      @subscription.build_location(@location.attributes)
      @subscription.build_user
      @fellow_posters_count = @subscription.find_nearby_posters.size
      @fellow_listeners_count = @subscription.find_nearby_listeners.size
      render action: 'new'
    else
      render action: 'search'
    end
  end

  def index
    redirect_to action: 'search'
  end

  def show
    @subscription = Subscription.find_by_uid(params[:uid])
    @fellow_posters_count = @subscription.find_nearby_posters.size
    @fellow_listeners_count = @subscription.find_nearby_listeners.size
  end

  def new
    @subscription = Subscription.new(subscription_params)
    @fellow_posters_count = @subscription.find_nearby_posters.size
    @fellow_listeners_count = @subscription.find_nearby_listeners.size
  end

  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      SubscriptionMailer.registration_email(@subscription).deliver_later
      flash[:success] = t('.success')
      redirect_to action: 'show', uid: @subscription.uid
    else
      @fellow_posters_count = @subscription.find_nearby_posters.size
      @fellow_listeners_count = @subscription.find_nearby_listeners.size
      render action: 'new'
    end
  end

  private
    def subscription_params
      params.require(:subscription).permit([user_attributes: [:email],
                                            topic_attributes: [:name],
                                            location_attributes: [:latitude,
                                                                  :longitude,
                                                                  :name,
                                                                  :radius_length,
                                                                  :radius_units]])
    end

    def topic_params
      params.require(:topic).permit([:name])
    end

    def location_params
      params.require(:location).permit([:latitude,:longitude,:name,:radius_length,:radius_units])
    end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def link_to_alternate_search
    if params[:map]
      link_to "Lo-fi Version", simple_form_path
    else
      link_to "Interactive Map", map_path
    end
  end

  def units_array
    [
      [t('measurements.km.text'), "km"],
      [t('measurements.m.text'), "m"],
      [t('measurements.mi.text'), "mi"],
      [t('measurements.ft.text'), "ft"]
    ]
  end
  def start_or_join_conversation(start, join)
    if @fellow_listeners_count.zero?
      start
    else
      join
    end
  end
  def subscription_attrs_for_localization
    {
      topic_name: @subscription.topic.name,
      radius_length: @subscription.location.radius_length,
      radius_units: @subscription.location.radius_units,
      location_name: @subscription.location.name
    }
  end
  def subscription_attrs_for_localization_with_count(count)
    subscription_attrs_for_localization.merge({ count: count })
  end
  def sharing_domain
    "https://#{t('domain')}"
  end

  def topic_sharing_path
    "/t/#{@subscription.topic.uid}"
  end
  def topic_sharing_url
    sharing_domain + topic_sharing_path
  end
  def topic_sharing_link
    link_to topic_sharing_url, topic_sharing_path
  end

  def sharing_title_and_desc
    attrs = { topic_name: @topic.name, location_name: @location.name }
    if @topic_uid.present? and @location_uid.present?
      provide(:title, t('subscriptions.search.topic_and_location_title', attrs))
      provide(:description, t('subscriptions.search.topic_and_location_description', attrs))
    else
      if @topic_uid.present?
        provide(:title, t('subscriptions.search.topic_title', attrs))
        provide(:description, t('subscriptions.search.topic_description', attrs))
      else
        provide(:description, t('subscriptions.search.base_description'))
      end
    end
  end

  def topic_and_location_sharing_path
    "/t/#{@subscription.topic.uid}/l/#{@subscription.location.uid}"
  end
  def topic_and_location_sharing_url
    sharing_domain + topic_and_location_sharing_path
  end
  def topic_and_location_sharing_link
    link_to topic_and_location_sharing_url, topic_and_location_sharing_path
  end

end

app/views/subscriptions/new.html.erb
<% provide(:title, t('.title', subscription_attrs_for_localization)) %>
<% provide(:description, t('.description', subscription_attrs_for_localization)) %>

<div class="content-blok">
  <h2>
    <%= t('.confirmation_heading', topic_name: @subscription.topic.name) %>
  </h2>
  <p>
    <%= t('.confirmation_html', topic_name: @subscription.topic.name,
                                radius_length: @subscription.location.radius_length,
                                radius_units: @subscription.location.radius_units,
                                location_name: @subscription.location.name,
                                start_or_join: start_or_join_conversation("start", "join")) %>
  </p>
  <aside>
    <p>
      <%= t('.confirmation_disclaimer_html') %>
    </p>
  </aside>
</div>
<%= render 'shared/errors' %>
<%= form_for @subscription, url: subscriptions_path do |f| %>
  <div class="pure-g fields-blok">
    <%= f.fields_for :topic do |topic| %>
      <%= topic.hidden_field :name %>
    <% end %>
    <%= f.fields_for :location do |location| %>
      <%= location.hidden_field :name %>
      <%= location.hidden_field :latitude %>
      <%= location.hidden_field :longitude %>
      <%= location.hidden_field :radius_length %>
      <%= location.hidden_field :radius_units %>
    <% end %>
    <div class="pure-u-1">
      <%= f.fields_for :user do |user| %>
        <div class="field">
          <%= image_tag 'envelope.svg' %>
          <%= user.label :email, t('.email_label') %>
          <%= user.text_field :email %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="actions content-blok">
    <%= f.submit t('.submit_label', start_or_join: start_or_join_conversation("Start", "Join")) %>
  </div>
<% end %>

app/views/subscriptions/search.html.erb
<% sharing_title_and_desc %>

<% if @topic.errors.any? or @location.errors.any? %>
  <div id="error-explanation" class="content-blok">
    <ul>
      <% @topic.errors.each do |attr, msg| %>
        <li><%= msg %></li>
      <% end %>
      <% @location.errors.each do |attr, msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag results_subscriptions_path do %>
  <div class="pure-g fields-blok">
    <%= fields_for @topic do |topic| %>
      <div class="pure-u-1 pure-u-lg-1-3">
        <div class="field">
          <%= image_tag 'heart.svg' %>
          <%= topic.label :name, t('.topic_label') %>
          <%= topic.text_field :name, class: 'topic-field auto-field', placeholder: t('.topic_placeholder') %>
        </div>
      </div>
    <% end %>
    <%= fields_for @location do |location| %>
      <div class="pure-u-1 pure-u-lg-1-3">
        <div class="field">
          <%= image_tag 'map.svg' %>
          <%= location.label :name, t('.location_label') %>
          <%= location.text_field :name, class: 'location-field auto-field', placeholder: t('.location_placeholder') %>
        </div>
      </div>
      <%= location.hidden_field :latitude %>
      <%= location.hidden_field :longitude %>
      <!-- <div id="map"></div> -->
      <div class="pure-u-1 pure-u-lg-1-3">
        <div class="field">
          <%= image_tag 'binoculars.svg' %>
          <%= location.label :radius_length, t('.radius_label') %>
          <%= location.number_field :radius_length, class: 'radius-length-field', placeholder: t('.radius_length_placeholder') %>
          <%= location.select :radius_units, units_array, {}, class: 'radius-units-select' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="actions content-blok">
    <%= submit_tag t('.submit_label') %>
  </div>
<% end %>

app/views/subscriptions/show.html.erb
<% provide(:title, t('.title', subscription_attrs_for_localization)) %>
<% provide(:description, t('.description', subscription_attrs_for_localization)) %>


<div class="content-blok">
  <h2>
    <%= t('.summary_heading', topic_name: @subscription.topic.name) %>
  </h2>
  <p>
    <%= t('.summary_html', subscription_attrs_for_localization) %>
  </p>
</div>
<div class="content-blok">
  <h3>
    <%= t('.getting_started_heading') %>
  </h3>
  <h4>
    <%= t('.getting_started_html_1') %>
  </h4>
  <p>
    <%= t('.getting_started_html_2', subscription_attrs_for_localization) %>
  </p>
  <% if false %>
  <aside>
    <p>
      <%= t('.conversations_html', subscription_attrs_for_localization_with_count(@fellow_posters_count)) %>
    </p>
  </aside>
  <% end %>
  <h4>
    <%= t('.starting_conversations_heading') %>
  </h4>
  <p>
    <%= t('.starting_conversations_html', subscription_attrs_for_localization) %>
  </p>
  <%= link_to "#{@subscription.uid}@#{t('mail_domain')}", "mailto:#{@subscription.uid}@#{t('mail_domain')}", class: "email-conversation-link" %>
  <aside>
    <p>
      <%= t('.listeners_html', subscription_attrs_for_localization_with_count(@fellow_listeners_count)) %>
    </p>
  </aside>
</div>
<div class="content-blok">
  <h3>
    <%= t('.sharing_heading') %>
  </h3>
  <p>
    <%= t('.sharing_html', subscription_attrs_for_localization) %>
  </p>
  <h4>
    <%= t('.share_without_location_heading') %>
  </h4>
  <div>
    <%= text_field_tag "topic_sharing_link", topic_sharing_url, readonly: true, class: "sharing-url" %>
  </div>
  <div class="sharing-social-links">
    <a class="sharing-social" href="<%= topic_sharing_url %>">URL</a>
    <a class="sharing-social" href="https://www.facebook.com/sharer/sharer.php?u=<%= topic_sharing_url %>">Facebook</a>
    <a class="sharing-social" href="https://twitter.com/home?status=<%= topic_sharing_url %>">Twitter</a>
    <a class="sharing-social" href="https://plus.google.com/share?url=<%= topic_sharing_url %>">Google+</a>
  </div>
  <h4>
    <%= t('.share_with_location_heading') %>
  </h4>
  <div>
    <%= text_field_tag "topic_and_location_sharing_link", topic_and_location_sharing_url, readonly: true, class: "sharing-url" %>
  </div>
  <div class="sharing-social-links">
    <a class="sharing-social" href="<%= topic_and_location_sharing_url %>">URL</a>
    <a class="sharing-social" href="https://www.facebook.com/sharer/sharer.php?u=<%= topic_and_location_sharing_url %>">Facebook</a>
    <a class="sharing-social" href="https://twitter.com/home?status=<%= topic_and_location_sharing_url %>">Twitter</a>
    <a class="sharing-social" href="https://plus.google.com/share?url=<%= topic_and_location_sharing_url %>">Google+</a>
  </div>
</div>

<div class="content-blok">
  <h3>
    <%= t('.additional_subscription_heading') %>
  </h3>
  <%= link_to t('.additional_subscription_html'), search_subscriptions_path %>
</div>

<% if false #if Rails.env.development? %>
<div class="content-blok">
  <ul>
    <li>New subscription: <%= @subscription.uid %></li>
    <li><%= @subscription.topic.name %>: <%= @subscription.topic.uid %></li>
    <li><%= @subscription.location.name %>: <%= @subscription.location.uid %></li>
    <li><%= @subscription.user.email %>: <%= @subscription.user.uid %></li>
  </ul>
</div>
<% end %>