config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics, only: [:autocomplete] do
    collection do
      get :autocomplete, defaults: { format: 'json' }
    end
  end

  resources :locations, only: [:autocomplete] do
    collection do
      get :autocomplete, defaults: { format: 'json' }
    end
  end

  scope "(:locale)", locale: /en|ja/ do
    resources :subscriptions, except: [:destroy], param: :uid do
      collection do
        get :search
        post :results
      end
    end

    resources :rich_subscriptions, except: [:destroy, :index], param: :uid

    resources :simple_search, except: [:destroy], param: :uid

    get '/unsubscribe', to: 'cancellations#new'
    post '/unsubscribe', to: 'cancellations#submit'
    get '/unsubscribing', to: 'cancellations#sent'
    get '/unsubscribe/:unsubscribe_uid', to: 'cancellations#destroy', as: 'unsubscriber'

    get '/about', to: 'static_pages#about'
    get '/privacy', to: 'static_pages#privacy'
  end

  get '/test_ip', to: 'subscriptions#test_ip'

  mount_griddler '/incoming/mail'

  get '/t/:topic_uid/l/:location_uid', to: 'subscriptions#search'
  get '/t/:topic_uid', to: 'subscriptions#search'

  get '/l/:location_uid/t/:topic_uid', to: 'subscriptions#search'
  get '/l/:location_uid', to: 'subscriptions#search'

  # get '/simple', to: 'subscriptions#new', defaults: { map: false }, as: :simple_form
  # get '/map', to: 'subscriptions#new', defaults: { map: true }, as: :map
  get '/:locale', to: 'subscriptions#search'
  root 'rich_subscriptions#new'

  match '*any', to: 'application#options', :via => [:options]

end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to t('.home'), root_path %></li>
      <li><%= link_to t('.about'), about_path %></li>
      <li><%= link_to t('.unsubscribe'), unsubscribe_path %></li>
      <% if Rails.env.development? %>
      <li><%= english_locale_link(I18n.locale) %></li>
      <li><%= japanese_locale_link(I18n.locale) %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div>
    <h1><%= t('.heading') %></h1>
  </div>
  <p><%= t('.subheading') %></p>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
  <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.1/build/grids-responsive-old-ie-min.css">
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= Gon::Base.render_data %>
    <%= asset_handler %>
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="<%= full_title(yield(:title)) %>" />
    <meta property="og:description" content="<%= full_description(yield(:description)) %>" />
    <meta property="og:image" content="https://raptmap.com/images/heart-marker-pano.png" />
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="main">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/full_screen_map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('layouts.header.heading') %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= Gon::Base.render_data %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    fingerprinted_asset('map'), media: 'all' %>
    <%= javascript_include_tag fingerprinted_asset('map') %>
    <%= render 'layouts/shim' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
    <div id="map"></div>
    <div id="test"></div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>